lexer grammar ExpLexer;
STRING : '"' ( '\\' . | ~["\\] )* '"';
LABEL : [a-zA-Zء-ي]([a-zA-Z0-9.ء-ي ]*[a-zA-Zء-ي])?;
BEGINGROUB : '(';
ENDGROUB : ')';
POW : '^';
TIMES : '*';
DIVIDE : '/';
PLUS : '+';
MINUS : '-';
NUMBER : [0-9]+('.'[0-9]*)?;
EQUALS : ' '*'='' '*;
VALUE_VAR : '#'[a-zA-Zء-ي][a-zA-Z0-9.ء-ي ]*[a-zA-Zء-ي];
FIND : [؟?];
ARABIC : [ء-ي];
STRINGMARK : '"';

WS : [\t\r ] -> skip;
NEWLINE : [\n]+;
COMMEA : ',';